version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: bbn-nutrition-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bbn-nutrition
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 